language: python
python:
  - '2.7'
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install firefox
  - cp mysite/mysite/settings/local_conf_example.py mysite/mysite/settings/local_conf.py
  - cp fab_settings.py.example fab_settings.py
  
install:
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - cd mysite/
  - python manage.py test
  - coverage run manage.py test
  
after_success: coveralls
